In [55]:
import pandas as pd

In [56]:
df = pd.read_csv('temp.csv', index_col='EventID')

df

,GameID,Season,DayNum,WTeamID,LTeamID,WPoints,LPoints,ElapsedSeconds,EventTeamID,EventPlayerID,EventType,PlayerID,PlayerName,TeamID,TeamName
EventID,,,,,,,,,,,,,,,
52,0,2010,7,1143,1293,0,0,338,1293,602781,miss1_free,602781,Ivan Aska,1293,Murray St
54,0,2010,7,1143,1293,10,10,338,1293,602781,made2_lay,602781,Ivan Aska,1293,Murray St

In [57]:
df1 = pd.read_csv('temp1.csv', index_col='EventID')
df1

,ElapsedSeconds,EventTeamID,GameID,EventPlayerID,Season,DayNum,WTeamID,LTeamID,WPoints,LPoints,EventType,PlayerID,PlayerName,TeamID,TeamName,madeFT,attFT
EventID,,,,,,,,,,,,,,,,,
54,338,1293,0,602781,2010,7,1143,1293,10,10,made2_lay,602781,Ivan Aska,1293,Murray St,0,1